version: '3.4'

services:
  marketforyou22.api:
    container_name: "marketforyou22.api"
    image: ${DOCKER_REGISTRY-}marketforyou22api
    build:
      context: .
      dockerfile: MarketForYou22.API/Dockerfile
    ports:
     - "35053:80"
     - "35054:443"
    environment:
     - ConnectionStrings__DefaultConnection=Server=mkfydata.db;Database=devdb;User Id=devdbuser;password=devdbpassword
    depends_on:
     - mkfydata.db
     
  mkfydata.db:
    container_name: "mkfydata.db"
    restart: on-failure 
    image: "postgis/postgis:14-3.3-alpine"
    ports:
      - "35050:5432"
    environment:
       - POSTGRES_USER=devdbuser
       - POSTGRES_DB=devdb
       - POSTGRES_PASSWORD=devdbpassword
    volumes:
        - mkfydata-db:/var/lib/postgresql/data

volumes:
  mkfydata-db:
